source 'https://rubygems.org'

gem 'cucumber',           '3.1.2'
gem 'rake',               '13.0.0'
gem 'rspec',              '3.9.0'
gem 'selenium-webdriver', '3.142.6'
gem 'watir',              '6.16.5'
